### ISSUE TITLE
Create database wireframe

### ISSUE THREAD

**Issue by isaiahpaviacruz** [Chelsea-Fullstack-Homework/Capstone-Project#1]
Loosey based on the provided image. Tailor the wireframe to a more e commerce experience.

![Image](https://github.com/Chelsea-Fullstack-Homework/Capstone-Project/assets/114330830/4594b9f1-8775-41f8-b695-8aa0f093dbc1)

**Comment by helseaCat** [comment]
![db_wireframe](https://github.com/Chelsea-Fullstack-Homework/Capstone-Project/assets/114330830/eb5238ba-32cc-42a8-b1bf-460a53602e9b)

created wireframe
